#!/bin/bash

# Check if an application is specified
if [ -z "$1" ]; then
    echo "Usage: $0 URL"
    exit 1
fi

yt-dlp -x --default-search "ytsearch" --audio-format mp3 -f bestaudio -o '%(playlist_autonumber)02d - %(title)s.%(ext)s' --embed-thumbnail --parse-metadata 'playlist_index:%(track_number)s' --add-metadata --embed-metadata $@
