#!/usr/bin/python

import sys
import subprocess
import sqlite3
from datetime import datetime

datafile = "./notes.sqlite"

action = sys.argv[1] if len(sys.argv) > 1 and sys.argv[1] else "read"
conn = sqlite3.connect(datafile)
match action:
    case "read":
        sql_script = """
        SELECT
            rowid AS id,
            CASE 
                WHEN status = 'PEND' THEN ' '
                WHEN status = 'DEFR' THEN 'D'
                WHEN status = 'FAIL' THEN 'F'
                ELSE 'x' END AS '[ ]',
            strftime('%d/%m', created_at) AS created_at,
            detail,
            result
        FROM todo
        WHERE status = 'PEND';
        """

        # Execute safely without shell=True
        res = subprocess.run(
            ["sqlite3", "-header", "-box", datafile],
            input=sql_script,
            capture_output=True,
            text=True,
            check=True
        )
        print(res.stdout)
    case "create":
        detail = sys.argv[2]
        clss = sys.argv[3] if len(sys.argv) > 3 and sys.argv[3] else "GENERIC"  
        series = sys.argv[4] if len(sys.argv) > 4 and sys.argv[4] else "GENERIC"
        now = datetime.now().isoformat()
        conn.execute("INSERT INTO todo (status,detail,class,series,created_at) VALUES (?,?,?,?,?);", ("PEND",detail,clss,series,now))
        conn.commit()
    case "delete":
        rowid = sys.argv[2]
        conn.execute("DELETE FROM todo WHERE rowid=?",(rowid,))
        conn.commit()
    case "done":
        rowid = sys.argv[2]
        result = sys.argv[3] if len(sys.argv) > 3 else ''
        now = datetime.now().isoformat()
        conn.execute("UPDATE todo SET status=?,done_at=?,result=? WHERE rowid=?;", ("DONE",now,result,rowid))
        conn.commit()
    case "defer":
        rowid = sys.argv[2]
        now = datetime.now().isoformat()
        conn.execute("UPDATE todo SET status=?,done_at=? WHERE rowid=?;", ("DEFR",now,rowid))
        conn.commit()
    case "edit":
        """
        rowid = sys.argv[2]
        detail = sys.argv[2]
        clss = sys.argv[3] if len(sys.argv) > 3 and sys.argv[3] else "GENERIC"  
        series = sys.argv[4] if len(sys.argv) > 4 and sys.argv[4] else "GENERIC"
        now = datetime.now().isoformat()
        conn.execute("UPDATE todo SET status=?,done_at=? WHERE rowid=?;", ("DONE",now,rowid))
        """
        pass
    case _:
        query = " ".join(sys.argv[1:])
        query = f'echo "{query}" | sqlite3 -header -box ' + datafile
        result = subprocess.run(
            query,
            shell=True,
            capture_output=True,
            text=True,
            check=True
            )
        print(result.stdout)
conn.close()
