#!/bin/bash
ffmpeg \
    -use_wallclock_as_timestamps 1 \
    -i http://192.168.110.247:4747/video \
    -c copy \
    -f segment \
    -segment_time 60 \
    -reset_timestamps 1 \
    -strftime 1 \
    "video_%Y-%m-%d_%H-%M-%S.mkv"

: <<'BLOCK_COMMENT'
ffmpeg \
    -use_wallclock_as_timestamps 1 \
    -i http://192.168.110.247:4747/video \
    -c copy \
    -f segment \
    -segment_time 60 \
    -reset_timestamps 1 \
    -strftime 1 \
    "video_%Y-%m-%d_%H-%M-%S.mkv"

  ffmpeg -fflags +genpts \
  -i http://192.168.110.247:4747/video \
  -c:v libx264 -preset veryfast -crf 23 \
  -f segment \
  -segment_time 60 \
  -reset_timestamps 1 \
  -strftime 1 \
  "video_%Y-%m-%d_%H-%M-%S.mp4"
BLOCK_COMMENT


